### ISSUE TITLE
Flatpak seems to be broken

### ISSUE THREAD

**Issue by scrabsha** [hmlendea/geforcenow-electron#81]
Hi,
I'm trying `geforcenow-electron` using flatpak and the app does not start.
```none
$ flatpak run io.github.hmlendea.geforcenow-electron
[2 zypak-helper] exec failed for /app/geforcenow-electron/node_modules/electron/dist/electron /app/geforcenow-electron/geforcenow: No such file or directory (errno 2)
```

I'm running Fedora 34 Gnome with Wayland. I installed `geforcenow-electron` from the Gnome Software boutique. Other flatpak work fine.

Please let me know if you want more details about my setup :)

**Comment by hmlendea** [comment]
Version 1.1.7 should be fixed once it's up on Flathub. Let me know how it goes.

**Comment by k4n30** [comment]
`$ flatpak list | grep gefo`
`GeForce Now Electron	io.github.hmlendea.geforcenow-electron	1.1.7	stable	system`

`$ flatpak run io.github.hmlendea.geforcenow-electron`
`[2 zypak-helper] exec failed for /app/geforcenow-electron/node_modules/electron/dist/electron /app/geforcenow-electron/geforcenow-electron: No such file or directory (errno 2)
`

**Comment by CBx86** [comment]
> Version 1.1.7 should be fixed once it's up on Flathub. Let me know how it goes.

Hey!
Problem persist on io.github.hmlendea.geforcenow-electron 1.1.7
[2 zypak-helper] exec failed for /app/geforcenow-electron/node_modules/electron/dist/electron /app/geforcenow-electron/geforcenow-electron: No such file or directory (errno 2)
Many thanks! Have a nice week.
